### ISSUE TITLE
새로운 친바 이벤트 API 스펙과 맞추기

### ISSUE THREAD

**Issue by Jiwon-Woo** [Together42/frontend#119]
### ToDo
- [x] `/api/together` -> `/meetups`

- [x] `GET /api/together/matching` && `GET /api/together/matching/:id` 삭제 (`GET /meetups/:id`로 대체)
  -  단, `NewPostingModal.tsx` & `SelectModal.tsx` 수정 보류
  -  완벽히 대체가 불가하며 게시판은 잠시 닫힐 예정이기 때문

- [x] `GET /meetups` 응답을 `data: { EventList: EventType[] } ` -> `data: EventType[]` 로 변경 (EventList 키값 제외)

- [x] `POST /meetups/attendance` -> `POST /meetups/${eventId}/attendance`

- [x] `DELETE /meetups/attendance/${eventId}` -> `DELETE /meetups/${eventId}/attendance`

- [x] `POST /meetups` 이후, 생성자가 이벤트 신청 API 요청하는 로직 삭제 (백엔드에서 트랜잭션으로 처리)

- [x] `POST /meetups/matching` -> `POST /meetups/${selectedEvent.id}/matching`

- [x] `POST /meetups/${selectedEvent.id}/matching` 요청시 보내는 `teamNum` 타입을 string -> number 변경
